# Code for the 1st week

## 1) Intro to NumPy

In [2]:
import numpy as np

In [12]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))

#avg value for columns
avg = np.mean(X, axis=0) 

#std deviation for every column
avg_deviation = np.std(X, axis=0)

X_normalized = ((X - avg)/avg_deviation)

print('In first array NOT_NORMALIZED, in the second NORMALIZED \n\n')
print (X[0], X_normalized[0], sep='\n\n')

In first array NOT_NORMALIZED, in the second NORMALIZED 


[ 18.24888109  15.09645701  11.48757725  10.73625233  -1.66127747
   4.34368645 -12.07199442  16.58340481  -4.4989423   -6.09736253
  -1.35077829 -13.71513219   3.35534664  14.38397528   0.41629405
   3.15754774   6.5713494   13.66677866   5.83365799   7.73690088
  -2.29028776   9.01018292   3.64493189  19.51811344  -6.21030918
   9.80126088  -5.30374433  10.35184879  13.72662792   2.71660243
 -13.97080464  -0.27637413  -3.86049693   3.98180436  12.20890901
 -12.44486963  11.38360291  -3.33943709  -8.10185238  -4.82887717
   6.71741596  -6.50335408  -1.49387586  10.0744722    8.02636718
   4.43092031   0.54132437  10.20449164   6.63565315   7.51304238]

[ 1.66547839  1.37763774  1.05329159  0.96080457 -0.26873981  0.28969427
 -1.36753085  1.54692726 -0.57020085 -0.71438987 -0.25469444 -1.50087096
  0.2754817   1.2942238  -0.07095294  0.23044961  0.59026551  1.15662602
  0.51762091  0.6979856  -0.31848173  0.80620668  0.30025135

In [15]:
sums = np.sum(X, axis=1)

#out = [i for i in range(len(sums)) if sums[i] > 10]
#print(out, sep=' ')

out = np.nonzero(sums > 10)
#print(out)

In [19]:
# Identity matrices
A = np.eye(3)
B = np.eye(3)

res = np.vstack((A, B))
print(res)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2) Preprocessing data in Pandas