## Intro to NumPy

In [1]:
import numpy as np

### Normalizing data

In [15]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))

#avg value for columns
avg = np.mean(X, axis=0) 

#std deviation for every column s
avg_deviation = np.std(X, axis=0)
print(X)

X_normalized = ((X - avg)/avg_deviation)
print (X_normalized)

[[  0.94382783 -16.38824984   2.18909552 ...   8.70836398  -0.8813616
   10.86252756]
 [ 12.54411002   7.29657854   4.08977624 ...  12.58574039  17.07786621
   -3.25004565]
 [  0.32147947   7.38386784  -9.17830199 ...  -2.62356913   6.51704316
    8.20491191]
 ...
 [-14.09081235   3.57621619  -1.55839019 ... -14.55918635   1.3294061
   -3.11784101]
 [  3.94524397 -10.01789226  -8.76387087 ...  -8.47289044  -0.74311728
   14.46481218]
 [ -4.38324639  11.52442126   9.3040919  ...  -5.39529521   6.56007038
  -13.90312854]]
[[-0.02750101 -1.76546447  0.11140917 ...  0.78131507 -0.16244769
   0.99554629]
 [ 1.15894606  0.60868614  0.30091175 ...  1.1711276   1.66477654
  -0.34203355]
 [-0.0911532   0.61743596 -1.02194854 ... -0.35794227  0.59028759
   0.74365933]
 ...
 [-1.56520539  0.23575962 -0.26222444 ... -1.55789107  0.06248227
  -0.32950329]
 [ 0.27947613 -1.12690429 -0.98062873 ... -0.94600453 -0.14838231
   1.33696831]
 [-0.57234048  1.03248213  0.82079195 ... -0.63659811  0.5946653

In [20]:
sums = np.sum(X, axis=1)

#out = [i for i in range(len(sums)) if sums[i] > 10]
#print(out, sep=' ')

print(np.nonzero(sums > 10))

[array([  0,   1,   3,   4,   5,   6,   8,   9,  10,  11,  12,  14,  17,
        18,  19,  20,  21,  22,  24,  26,  27,  28,  30,  33,  36,  37,
        38,  41,  42,  43,  44,  47,  48,  50,  51,  52,  54,  56,  57,
        58,  60,  61,  62,  63,  64,  66,  68,  69,  70,  71,  72,  73,
        74,  75,  76,  77,  79,  81,  83,  84,  86,  87,  88,  90,  91,
        92,  93,  96,  97,  98,  99, 100, 101, 104, 105, 106, 107, 108,
       109, 110, 113, 118, 121, 123, 126, 127, 128, 129, 131, 132, 134,
       135, 137, 139, 140, 141, 142, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 172, 174, 176, 177, 178, 179, 180, 181,
       182, 183, 185, 186, 188, 190, 191, 194, 198, 199, 201, 203, 205,
       206, 208, 210, 211, 212, 213, 214, 215, 216, 218, 220, 221, 222,
       223, 224, 226, 227, 228, 229, 230, 231, 233, 234, 235, 239, 240,
       241, 242, 243, 244, 245, 246, 247, 248, 249, 251, 254, 2

In [24]:
A = np.eye(3)
B = np.eye(3)
res = np.vstack((A, B))

print(res)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
